### ISSUE TITLE
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.

### ISSUE THREAD

**Issue by yingdianRao** [succinctlabs/sp1-tendermint-example#12]
<img width="1360" alt="image" src="https://github.com/succinctlabs/sp1-tendermint-example/assets/163795768/261685bc-13c8-4177-af89-98f235e2df1a">

CHAIN_ID=11155111  RPC_URL=... PRIVATE_KEY=...CONTRACT_ADDRESS=... TENDERMINT_RPC_URL=127.0.0.1:26657  cargo run --bin operator

**Comment by ratankaliani** [comment]
Hey! If you follow the instructions in the `README` this should now be fixed 🙂, thanks for opening the issue. Feel free to open another one if you run into anything else.

https://github.com/succinctlabs/sp1-tendermint-example?tab=readme-ov-file#run-tendermint-operator-end-to-end
